// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkqHs9ZJw8jSEFWfxCGv-JoAkJUTSGias',
    appId: '1:1059168951877:android:c96fa6349bec26e0300d2c',
    messagingSenderId: '1059168951877',
    projectId: 'project-673dc',
    storageBucket: 'project-673dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZkIs6VZjQhRqU7vLNjdQQz6UnXOMmEYo',
    appId: '1:1059168951877:ios:e3ea050a3c4d5edf300d2c',
    messagingSenderId: '1059168951877',
    projectId: 'project-673dc',
    storageBucket: 'project-673dc.appspot.com',
    androidClientId: '1059168951877-b6stsihqa4106jdmf1ur3nb26vj6fv9u.apps.googleusercontent.com',
    iosClientId: '1059168951877-nokv1tkv6epqnl3rffsfggsdrr7ipdga.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
